name: flutter_bloc_firebase_basic_auth
description: A simple Flutter app using flutter_bloc, freezed classes, injectable, and Firebase.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.0.3
  injectable: ^1.5.3
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true
